name: transport_lan
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  gatekeeper_rate_limit:
    path: ../gatekeeper_rate_limit
  nsd: ^5.0.1
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_web_socket: ^2.0.0
  transport_interface:
    path: ../transport_interface
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6
